# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-06 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField(default=50.0)),
                ('pH', models.FloatField(default=7.0)),
                ('humidity', models.FloatField(default=50.0)),
                ('temperature', models.FloatField(default=25.0)),
                ('datetime', models.CharField(max_length=30)),
                ('devicecode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('country', models.CharField(choices=[('NPL', 'Nepal'), ('IND', 'India'), ('BAN', 'Bangladesh'), ('PAK', 'Pakistan'), ('BHU', 'Bhutan'), ('AFG', 'Afghanistan')], max_length=20)),
                ('devicecode', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
